name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image latest
      run: docker build . --file versions/latest/Dockerfile --tag rabbitmq-with-delayed-message-shovel-plugins:latest-$(date +%s)
